config/routes.rb
Rails.application.routes.draw do
  # devise_for :customers, skip: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  namespace :admin do
    root to: 'homes#top'
    resources :customers,only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
    resources :order_items, only: [:update]
    end
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    resource :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw]
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'

    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy, :destroy_all]
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
    get 'customers/my_page' => 'customers#show'

  end

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :product
  belongs_to :customer

end

app/models/catt_item.rb
class CattItem < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items, dependent: :destroy
   
   validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  has_many :orders, through: :order_details

  attachment :image

end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  # def new
  #   @genre = Genre.new
  # end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルの登録が完了しました"
      redirect_to request.referer
    else
       @genres = Genre.all
       render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "ジャンルの更新が完了しました"
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :image, :price, :genre_id, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @orders = @order.order_detail
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)
    if @order.order_status == "入金待ち"
       @order_details.each do |order_detail|
        order_detail.making_status = "着手不可"
        order_detail.save
      end
    end
    redirect_to admin_order_path
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    # @item = Item.find(params[:id])
    @items = Item.all.page(params[:page]).reverse_order
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end



 
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/items/edit.html.erb
<main>
  <div class="container">
    <div class="pt-5">
      <h3><span style="background-color:#dcdcdc">商品編集画面</span></h3>
      <%= form_with model: @item, url: admin_item_path, local: true do |f| %>

      <table class="table">
        <tr>
          <td>商品画像</td>
          <td><%= f.attachment_field :image %></td>
        </tr>
        <tr>
          <td>商品名</td>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= f.text_area :introduction %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= f.collection_select(:genre_id, Genre.all, :id, :name, prompt: "-- 選択してください --") %></td>
        </tr>
        <tr>
          <td>税抜価格</td>
          <td><%= f.text_field :price %>円</td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <td>
            <%= f.radio_button :is_active, true %>
            <%= f.label :is_active, "販売中", value: :true %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "販売停止中", value: :false %>
          </td>
        </tr>
      </table>

      <%= f.submit '変更を保存', class: "btn btn-success  mx-auto" %>
      <% end %>
    </div>
  </div>
</main>

app/views/admin/items/index.html.erb
<main>
  <div class="container">
    <div class="pt-5">
      <h3><span style="background-color:#dcdcdc">商品一覧</span></h3>
      <%= link_to "新規登録",new_admin_item_path ,class: "float-right" %>
        <table class="table">
          <thead>
            <tr>
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜き価格</th>
              <th>ジャンル</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td>
                <%= link_to admin_item_path(item.id) do %>
                  <%= item.name %>
                <% end %>
              </td>
              <td><%= item.price %></td>
              <td><%= item.genre.name %></td>
              <td>
                <% if item.is_active == true %>
                  <p>販売中</p>
                <% elsif item.is_active == false %>
                  <p>販売停止中</p>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @items %>
    </div>
  </div>
</main>

app/views/admin/items/new.html.erb
<main>
  <div class="container">
    <div class="pt-5">
      <h3><span style="background-color:#dcdcdc">商品新規登録</span></h3>
      <%= form_with model: @item, url: admin_items_path, local: true do |f| %>

      <table class="table">
        <tr>
          <td>商品画像</td>
          <td><%= f.attachment_field :image %></td>
        </tr>
        <tr>
          <td>商品名</td>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= f.text_area :introduction %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= f.collection_select(:genre_id, Genre.all, :id, :name, prompt: "-- 選択してください --") %></td>
        </tr>
        <tr>
          <td>税抜価格</td>
          <td><%= f.text_field :price %>円</td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <td>
            <%= f.radio_button :is_active, true %>
            <%= f.label :is_active, "販売中", value: :true %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "販売停止中", value: :false %>
          </td>
        </tr>
      </table>

      <%= f.submit '新規登録', class: "btn btn-success  mx-auto" %>
      <% end %>
    </div>
  </div>
</main>

app/views/admin/items/show.html.erb
<main>
  <div class="container">
    <div class="pt-5">
      <h3><span style="background-color:#dcdcdc">商品詳細</span></h3>
        <%= attachment_image_tag @item, :image, format: 'jpeg', fallback: 'no_image.jpg', size:'300x200'%>
        <table class="table">
          <tr>
            <th>商品名</th>
            <th><%= @item.name %></th>
          </tr>
          <tr>
            <th>商品説明</th>
            <th><%= @item.introduction %></th>
          </tr>
          <tr>
            <th>ジャンル</th>
            <th><%= @item.genre.name %></th>
          </tr>
          <tr>
            <th>税込み価格<br>(税抜き価格)</th>
            <th><%= (@item.price*1.10).round %>(<%= @item.price %>)円</th>
          </tr>
          <tr>
            <th>販売ステータス</th>
            <th>
              <% if @item.is_active == true %>
              <strong>販売中</strong>
              <% elsif @item.is_active == false %>
              <strong>販売停止中</strong>
              <% end %>
            </th>
          </tr>
        </table>

        <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %>

    </div>
  </div>
</main>

app/views/items/index.html.erb
<!--商品一覧-->
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class = "col-4"><b>商品一覧</b>　(全<%= @items.count %>件)</div>
  </div>
  <div class="row">
    <% @items.each do |item| %>
    <div class = "col-3">
      <div><%#= attachment_image_tag item, :image, fallback: "no_image.jpg", size: "40x40" %>
      </div>
      <div><%= link_to item.name,item_path(item.id) %></div>
      <div>¥<%= item.price %></div>
    </div>
    <% end %>
  </div>
  <div class="row">
    <div><%= paginate @items %></div>
  </div>
</div>

app/views/items/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-7">
      <tbody>
        <div class="card mb-3" style="max-width: 540px;">
          <div class="row no-gutters">
            <div class="col-md-4">
              <svg class="bd-placeholder-img" width="100%" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em">
                attachment_image_tag @item, :image, fallback: "no_image.jpg", size: "40x40"</text></svg>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">@item.name</h5>
                <p class="card-text">@item.introduction</p>
                <p><b>￥@item.price*1.10税込価格"</b>(税込)</p>
                <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
                <div>
                  <%= form_with model: @cart_item, local:true do |f| %>
                    <!-- 以下の一行がプルダウンを実装するためのコード（追記部分） -->
                    <%= f.select :amount, [["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"], ["6", "6"], ["7", "7"], ["8", "8"], ["9", "9"], ["10", "10"], ["50", "50"]], include_blank: "個数選択" %>
                    <%= f.submit '　カートに入れる　', class:"btn btn-sm btn-success" %>
                  <% end %>
              </div>
              </div>
            </div>
          </div>
        </div>
      </tbody>
    </div>
  </div>
</div>