config/routes.rb
Rails.application.routes.draw do
  # devise_for :customers, skip: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  namespace :admin do
    root to: 'homes#top'
    resources :customers,only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
    resources :order_items, only: [:update]
    end
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    resource :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw]
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'

    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy, :destroy_all]
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
    get 'customers/my_page' => 'customers#show'

  end

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :product
  belongs_to :customer

end

app/models/catt_item.rb
class CattItem < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items, dependent: :destroy
   
   validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  has_many :orders, through: :order_details

  attachment :image

end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])

  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
       flash[:notice] = "会員情報の更新が完了しました"
       redirect_to admin_customers_path
    else
      render :edit
    end

  end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number ,:email,:is_valid)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :image, :price, :genre_id, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    # @item = Item.find(params[:id])
    @items = Item.all.page(params[:page]).reverse_order
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end



 
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/customers/edit.html.erb
<div class="ml-5">
<h2>登録情報編集</h2>
<%= render 'layouts/error', errorinstance: @customer %>
<%= form_with model:[:admin,@customer], local:true do |f| %>
 <table>
    <thead></thead>
    <tbody>
      <tr>
        <div class="field">
         <td><%= f.label :"名前" %>　　　　　　　　　　<%= f.label :"(姓)" %> </td>
         <td><%= f.text_field :first_name, autofocus: true %>　　　<%= f.label :"(名)" %> </td>
         <td><%= f.text_field :last_name, autofocus: true %></td>
        </div>
      </tr>

      <tr>
        <div class="field">
          <td><%= f.label :"フリガナ" %>　　　　　　　<%= f.label :"(セイ)" %></td>
          <td><%= f.text_field :first_kana, autofocus: true %>　　<%= f.label :"(メイ)" %></td>
          <td><%= f.text_field :last_kana, autofocus: true %></td>
        </div>
      </tr>

      <tr>
        <div class="field">
          <td><%= f.label :"メールアドレス" %></td>
          <td><%= f.email_field :email, autofocus: true, autocomplete: "email" %></td>
        </div>
      </tr>

      <tr>
        <div class="field">
        <td><%= f.label :"郵便番号(ハイフンなし)" %></td>
        <td><%= f.text_field :post_code, autofocus: true %></td>
        </div>
      </tr>

      <tr>
        <div class="field">
         <td> <%= f.label :"住所" %></td>
         <td> <%= f.text_field :address, autofocus: true %></td>
        </div>
      </tr>

      <tr>
        <div class="field">
         <td><%= f.label :"電話番号(ハイフンなし)" %></td>
         <td><%= f.text_field :phone, autofocus: true %></td>
        </div>
      </tr>

      <tr>
        <td><%#= f.label :会員ステータス %></td>
        <td>
          <%#= f.radio_button "is_valid","有効"%>
          <%#= f.label "is_valid", "有効" %>
          <%#= f.radio_button "is_valid","退会" %>
          <%#= f.label "is_valid", "退会" %>
        </td>
      </tr>

      <tr>
        <td></td>
        <div class="actions">
          <td> <%= f.submit "更新",class: 'btn btn-success btn-block' %></td>
        </div>
      </tr>

    </tbody>
  </table>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="ml-5">
<h2>
  <td>会員一覧</td>
</h2>
  <table class='table table-hover'>
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>

      </tr>
    </thead>
    <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td>
          <%= link_to admin_customer_path(customer.id) do %>
            <%= customer.first_name %><%= customer.last_name %>
          <% end %>
        </td>
        <td><%= customer.email %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div><%= paginate @customers %></div>
</div>

app/views/admin/customers/show.html.erb
<div class="ml-5">
<h2><%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細</h2>

  <table>
    <tbody>

      <tr>
        <td>会員ID　　　　　</td>
        <td><%= @customer.id %></td>
      </tr>

      <tr>
        <td>氏名</td>
        <td><%= @customer.first_name %> <%= @customer.last_name %></td>
      </tr>

      <tr>
        <td>フリガナ</td>
        <td><%= @customer.first_name_kana %> <%= @customer.last_name_kana %></td>
      </tr>

      <tr>
        <td>郵便番号</td>
        <td><%= @customer.postal_code %></td>
      </tr>

      <tr>
        <td>住所</td>
        <td><%= @customer.address %></td>
      </tr>

      <tr>
        <td>電話番号</td>
        <td><%= @customer.telephone_number %></td>
      </tr>

      <tr>
        <td>メールアドレス</td>
        <td><%= @customer.email %></td>
      </tr>

      <tr>
        <!--<td>会員ステータス</td>-->
        <td><%#= @customer.is_deleted %></td>
      </tr>

      <tr>
        <td><%= link_to '編集する',edit_admin_customer_path,class: "btn btn-outline-secondary btn-success text-white" %></td>
        <!--<td>%= link_to '注文履歴一覧を見る', admins_orders_path(order_sort: 0), customer_id: @customer.id, class: "btn btn-outline-secondary text-dark" %></td>-->
        <td>
          <%= form_with model:@order, url: admin_orders_path, customer_id: @customer.id, local:true do |f| %>
          <%= f.hidden_field :order_sort, :value => 0 %>
          <%= f.hidden_field :customer_id, :value => @customer.id %>
          <%= f.submit '注文履歴一覧を見る',class: "btn btn-outline-secondary btn-primary text-white"%>
          <% end %>
        </td>
      </tr>

    </tbody>
  </table>
</div>
<!--%= link_to '注文履歴一覧を見る（リンク先未作成）', admins_orders_path(order_sort: 0),class: "btn btn-outline-secondary text-dark" %>-->
<!--%= form_with model:@order, url: admins_orders_path(order_sort: 0), customer_id: @customer.id, local:true do |f| %>-->
<!--%= f.hidden_field :customer_id, :value => @customer.id %>-->
<!--%= f.submit '注文履歴一覧を見る'%>-->
<!--% end %>-->