config/routes.rb
Rails.application.routes.draw do
  # devise_for :customers, skip: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  namespace :admin do
    root to: 'homes#top'
    resources :customers,only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
    resources :order_items, only: [:update]
    end
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    resource :customers, only: [:show, :edit, :update, :unsubscribe, :withdraw]
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#complete'

    resources :orders, only: [:new, :create, :index, :show]
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy, :destroy_all]
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
    get 'customers/my_page' => 'customers#show'

  end

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :product
  belongs_to :customer

end

app/models/catt_item.rb
class CattItem < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items, dependent: :destroy
   
   validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  has_many :orders, through: :order_details

  attachment :image

end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  belongs_to :order
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    # @item = Item.find(params[:id])
    @items = Item.all.page(params[:page]).reverse_order
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end



 
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/_error.html.erb
<% if errorinstance.errors.any? %>
  <div class="error_explanation">
    <h2><%= errorinstance.errors.count %> error prohibited this obj from being saved:</h2>
    <ul>
      <% errorinstance.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Naganocake</title>
    <%= csrf_meta_tag %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



  </head>


  <body>
    <header class>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
            <%= link_to image_tag('logo.png'), '/' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <li><%= link_to 'マイページ', customers_my_page_path,class: "btn btn-outline-dark text-dark m-2" %></li>
              <li><%= link_to '商品一覧', items_path,class: "btn btn-outline-dark text-dark m-2" %></li>
              <li><%= link_to 'カート', cart_items_path,class: "btn btn-outline-dark text-dark m-2" %></li>
              <li><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete,class: "btn btn-outline-dark text-dark m-2" %></li>

            <% elsif admin_signed_in? %>
              <li><%= link_to '商品一覧', admin_items_path,class: "btn btn-outline-dark text-dark m-2" %></li>
              <li><%= link_to '会員一覧', admin_customers_path,class: "btn btn-outline-dark text-dark m-2" %></li>
              <li><%= link_to '注文履歴一覧', admin_root_path,class: "btn btn-outline-dark text-dark m-2" %></li>
              <li><%= link_to 'ジャンル一覧', admin_genres_path,class: "btn btn-outline-dark text-dark m-2" %></li>
              <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark text-dark m-2" %></li>

              <% else %>
              <li><%= link_to 'About', about_path,class: "btn btn-outline-dark text-dark m-2" %></li>
              <li><%= link_to '商品一覧', items_path,class: "btn btn-outline-dark text-dark m-2" %></li>
              <li><%= link_to '新規登録', new_customer_registration_path,class: "btn btn-outline-dark text-dark m-2" %></li>
              <li><%= link_to 'ログイン', new_customer_session_path,class: "btn btn-outline-dark text-dark m-2" %></li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div>　</div>
      <% flash.each do |message_type, message|%>
        <div class="flash_message">
        <%= content_tag :div, message, class: message_type %>
        </div>
      <% end %>

      <%= yield %>
    </main>
    <footer>
    </footer>
  </body>
</html>